name: update_data # basing on this article: https://towardsdatascience.com/simple-versioned-datasets-with-github-actions-bd7adb37f04b

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9 * 1,2,9-12 TUE' # updates every Tuesday in the months that NFL games are played

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get working copy
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install requirements
        run: |
          pip install requests
          pip install numpy
          pip install pandas
      - name: Update data
        run: |
          python update_data.py
      - name: Commit and push if it changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git pull
          git add -A
          timestamp=$(date -u)
          git commit -m "Last updated: ${timestamp}" || exit 0
          git push origin main || echo "No changes to commit"
